### ISSUE TITLE
Error: Unable to load valid module manifest data

### ISSUE THREAD

**Issue by DarkenedOrigins** [jessev14/pf2e-staves#26]
Error: Unable to load valid module manifest data from "https://github.com/jessev14/pf2e-staves/releases/download/1.2.5/module.json"
The requested manifest at "https://github.com/jessev14/pf2e-staves/releases/download/1.2.5/module.json" did not provide module manifest data.
    at Module.installPackage (file:///home/ubuntu/foundry/resources/app/dist/packages/views.mjs:1:1634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///home/ubuntu/foundry/resources/app/dist/server/views/setup.mjs:1:1980)
error @ setup.js:292

**Comment by DarkenedOrigins** [comment]
a refresh fixed it. weird closing.
