### ISSUE TITLE
Bug: Errors thrown while doing character creation with module active.

### ISSUE THREAD

**Issue by esheyw** [jessev14/pf2e-staves#8]
Setting up a new world, first time activating this module, building a couple of test characters, and staves is throwing a pair of errors every time I drop a Deity onto a player sheet:
```
foundry.js:747 TypeError: Cannot read properties of undefined (reading 'includes')
[Detected 1 package: pf2e-staves]
    at Object.fn (main.js:95:28)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at ClientDatabaseBackend._preDeleteDocumentArray (foundry.js:12917:47)
    at async ClientDatabaseBackend._deleteEmbeddedDocuments (foundry.js:12875:22)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:728
call @ foundry.js:706
_preDeleteDocumentArray @ foundry.js:12917
await in _preDeleteDocumentArray (async)
_deleteEmbeddedDocuments @ foundry.js:12875
delete @ commons.js:6856
await in delete (async)
deleteDocuments @ commons.js:6198
deleteDocuments @ main.bundle.js:1
await in deleteDocuments (async)
deleteEmbeddedDocuments @ commons.js:6364
deleteEmbeddedDocuments @ main.bundle.js:1
createDocuments @ main.bundle.js:1
await in createDocuments (async)
createEmbeddedDocuments @ commons.js:6328
_onDropItemCreate @ foundry.js:61606
_handleDroppedItem @ main.bundle.js:1
_handleDroppedItem @ main.bundle.js:1
_onDropItem @ main.bundle.js:1
await in _onDropItem (async)
_onDropItem @ main.bundle.js:1
await in _onDropItem (async)
_onDrop @ foundry.js:61518
_onDrop @ main.bundle.js:1
callback @ foundry.js:56837
_handleDrop @ foundry.js:56888
main.js:23 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
[Detected 1 package: pf2e-staves]
    at Object.fn (main.js:23:28)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12613:13)
    at foundry.js:12594:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:12594:33)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12499:17)
    at async ItemPF2e.createDocuments (commons.js:6110:23)```

this actor has nothing in their inventory yet, nor any spellcasting entries, just the ABC(D) set up.

**Comment by jessev14** [comment]
Appreciate the heads up. Fixed in 1.1.3.
